import { Pool } from "pg";
export declare const envString: (key: string, fallback?: string) => string;
export declare function createPoolFromEnv(): Pool;
export declare const AUTH_COOKIE_NAME = "fd_session";
export declare const AUTH_SESSION_DAYS: number;
export declare const AUTH_COOKIE_SECURE_MODE: string;
export declare const PUBLIC_AUTH_PATHS: Set<string>;
export declare const GOOGLE_WORKSPACE_CLIENT_ID: string;
export declare const GOOGLE_WORKSPACE_DOMAIN: string;
export declare const PYTHON_BIN: string;
export declare const PORT: number;
export declare const SOCIAL_PUBLIC_BASE_URL: string;
export declare const SOCIAL_SCHEDULER_ENABLED: boolean;
export declare const SOCIAL_SCHEDULER_INTERVAL_MS: number;
export type OllamaNodeKey = "msi-5070ti" | "alphabs" | "alphabs1" | "alphahs";
export type OllamaNodeConfig = {
    key: OllamaNodeKey;
    label: string;
    host: string;
    baseUrl: string;
    description: string;
};
export declare const DEFAULT_OLLAMA_NODE_KEY: OllamaNodeKey;
export declare const OLLAMA_NODE_CONFIGS: OllamaNodeConfig[];
export declare const resolveOllamaNode: (nodeKey?: string) => OllamaNodeConfig;
export declare const OLLAMA_BASE_URL: string;
export declare const OLLAMA_PRIMARY_NODE_LABEL: string;
export declare const OLLAMA_PRIMARY_MODEL: string;
export declare const ANTHROPIC_API_KEY: string;
export declare const BOTBOT_LOCAL_AI_URL: string;
export declare const BOTBOT_LOCAL_AI_TOKEN: string;
export declare const BOTBOT_LEDGER_TOKEN: string;
export declare const OPENAI_API_KEY: string;
export declare const OPENAI_BASE_URL: string;
export declare const OPENAI_FAST_MODEL: string;
export declare const OPENAI_BALANCED_MODEL: string;
export declare const BOTBOT_ENABLED: boolean;
